Update LICENSE
acoular/acoular pull request #221
Opened 2024-04-21 08:18 UTC by artpelling

I've regenerated the `LICENSE` file via the github generator interface. That way, the type of license can be detected by github and displayed nicely. It should say BSD-Clause 3 instead of view license on the right side as well as in the readme section of the main repo page.

2024-04-21 11:54 UTC, adku1173 requested changes
Thanks for the patch :). Similar to PR #223, the sidebar rendering does not seem to be correct (still 'view license' instead of 'BSD-3'). Don't know if these changes only become active after merging.

2024-04-21 11:54 UTC, adku1173 commented on LICENSE
> +Copyright (c) 2024, acoular
To be consistent, I would prefer to use the `Copyright (c) Acoular Development Team` statement without specifying a certain year. 
```suggestion
Copyright (c) Acoular Development Team
```

2024-04-22 09:03 UTC, artpelling commented
> Thanks for the patch :). Similar to PR #223, the sidebar rendering does not seem to be correct (still 'view license' instead of 'BSD-3'). Don't know if these changes only become active after merging.

Thats weird, same for me. I just ran `licensee`, which is used by gh to determine the license, on the repo locally and got:

``` shell
License:        NOASSERTION
Matched files:  LICENSE, README.md
LICENSE:
  Content hash:  0369877394f6b8ac27bf045ac22c1e9d204c259f
  License:       NOASSERTION
  Closest non-matching licenses:
    BSD-3-Clause similarity:        97.52%
    BSD-4-Clause similarity:        84.48%
    BSD-3-Clause-Clear similarity:  83.10%
README.md:
  Content hash:  a9ba7410d4c27eeafd6d27eb250802baaaed790a
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       BSD-3-Clause
  Closest non-matching licenses:
    WTFPL similarity:  5.56%
    0BSD similarity:   1.92%
    ISC similarity:    1.71%
```
for master and

``` shell
License:        BSD-3-Clause
Matched files:  LICENSE, README.md
LICENSE:
  Content hash:  a961b19cc6921d510e29a13b0ba1a826fcffe41c
  Attribution:   Copyright (c) Acoular Development Team
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       BSD-3-Clause
README.md:
  Content hash:  a9ba7410d4c27eeafd6d27eb250802baaaed790a
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       BSD-3-Clause
  Closest non-matching licenses:
    WTFPL similarity:  5.56%
    0BSD similarity:   1.92%
    ISC similarity:    1.71%
```

so lets hope that it works once merged?

2024-04-22 09:06 UTC, adku1173 approved these changes

2024-04-22 09:07 UTC, merged