Fix deprecation
acoular/acoular pull request #323
Opened 2024-10-08 08:50 UTC by adku1173

* Fix newly introduced deprecation warnings 
* use pytest instead of unittests in `test_classes.py`
* actively deprecate the use of the `beamformer` trait
* loose deprecation policy (newly introduced DeprecationWarnings will take effect three releases after introduction)

2024-10-08 14:54 UTC, esarradj requested changes

2024-10-09 07:53 UTC, adku1173 commented on tests/test_classes.py
>  """Implements testing of frequency beamformers."""
Indeed.

2024-10-09 07:54 UTC, adku1173 commented on tests/test_classes.py
> +all_classes = dir(ac)
This is now solved by parsing each submodule of Acoular

2024-10-09 08:03 UTC, esarradj approved these changes

2024-10-09 08:04 UTC, merged