Test traits dependencies
acoular/acoular pull request #374
Opened 2024-11-28 11:18 UTC by artpelling

### Description

### Reference issue

Closes #359 

### Checklist

- [x] I have read the [Contributing](https://www.acoular.org/contributing/index.html) section.
- [ x My branch is up-to-date with the *master* branch of the [Acoular repository](https://github.com/acoular/acoular).
- [x] My changes fulfill the [Code Quality](https://www.acoular.org/contributing/quality.html) standards.
- [ ] I have updated the [What's new](https://www.acoular.org/news/index.html) section the the [documentation](https://github.com/acoular/acoular/blob/master/docs/source/news/index.rst) explaining my changes.
- [x] I have appended myself to the [CITATION.cff](https://github.com/acoular/acoular/blob/master/CITATION.cff) file.

2024-11-28 16:07 UTC, artpelling commented
Currently waiting for a resolution of #375 before proceeding

2025-01-22 17:24 UTC, artpelling commented
@adku1173 I've removed `FlowField` from the regression test cases. Not sure if thats the way to go, though. If so, we might also have to delete some data?

2025-01-23 09:57 UTC, adku1173 requested changes

2025-01-23 09:57 UTC, adku1173 commented on acoular/environments.py
>          implemented here for the possibly most simple case: a quiescent fluid.
```suggestion
        """Provides the flow field as a function of the location.
```

2025-01-23 09:57 UTC, adku1173 commented on tests/unittests/test_classes.py
> +                    assert toplevel, type(obj).__name__ + '.' + tname
Better write a function that handles assert message formatting (function could be placed in /tests/utils.py).

2025-01-23 11:19 UTC, artpelling commented on acoular/environments.py
>          implemented here for the possibly most simple case: a quiescent fluid.
@esarradj @gherold Should we add something like `ZeroFlowField` or similar for this functionality?

2025-01-23 11:43 UTC, esarradj commented on acoular/environments.py
>          implemented here for the possibly most simple case: a quiescent fluid.
This would only make sense for testing purposes, e.g. comparing the results of a. That's why I hid this in the abstract base class. A bit sloppy, I guess. If we do not want the abstract base class to implement something here, it could also be removed without any replacement imho.

2025-01-23 13:36 UTC, adku1173 approved these changes

2025-01-23 17:04 UTC, esarradj approved these changes

2025-01-24 08:40 UTC, merged