Auto-assign pull request
acoular/acoular pull request #386
Opened 2024-11-29 16:43 UTC by jtodev

### Description

adds action that automatically assigns a team member to newly opened pull requests

### Checklist

- [x] I have read the [Contributing](https://www.acoular.org/contributing/index.html) section.
- [x] My branch is up-to-date with the *master* branch of the [Acoular repository](https://github.com/acoular/acoular).
- [x] My changes fulfill the [Code Quality](https://www.acoular.org/contributing/quality.html) standards.
- [x] I have updated the [What's new](https://www.acoular.org/news/index.html) section the the [documentation](https://github.com/acoular/acoular/blob/master/docs/source/news/index.rst) explaining my changes.
- [x] I have appended myself to the [CITATION.cff](https://github.com/acoular/acoular/blob/master/CITATION.cff) file.

2024-12-02 08:52 UTC, adku1173 requested changes

2024-12-02 09:44 UTC, artpelling requested changes
I am thinking that it would be nice to also have this for issues. It looks like it is not possible to do that with the current action. @jtodev Did you try https://github.com/wow-actions/auto-assign yet?

2024-12-02 09:45 UTC, adku1173 commented
@jtodev rebase required

2024-12-03 14:29 UTC, adku1173 approved these changes

2024-12-03 14:38 UTC, merged