Docstrings for grids.py
acoular/acoular pull request #404
Opened 2024-12-20 14:55 UTC by jtodev

### Description
New docstrings for grids.py
### Checklist

- [x] I have read the [Contributing](https://www.acoular.org/contributing/index.html) section.
- [x] My branch is up-to-date with the *master* branch of the [Acoular repository](https://github.com/acoular/acoular).
- [x] My changes fulfill the [Code Quality](https://www.acoular.org/contributing/quality.html) standards.
- [x] I have updated the [What's new](https://www.acoular.org/news/index.html) section the the [documentation](https://github.com/acoular/acoular/blob/master/docs/source/news/index.rst) explaining my changes.
- [x] I have appended myself to the [CITATION.cff](https://github.com/acoular/acoular/blob/master/CITATION.cff) file.

2025-01-08 10:05 UTC, artpelling requested changes
Nice work so far, thanks! I've left some comments.

Any method starting with an underscore, i.e. `_get_foo` does not need a docstring. They are not rendered by sphinx. Especially all setters and getters of properties. It would be nice if you could remove them. This should also spare you some work going forward :D. If there is a private method that performs more involved computations, we could explain those briefly with a code comment.

2025-01-15 09:17 UTC, artpelling requested changes

2025-01-17 13:16 UTC, jtodev commented on acoular/grids.py
> +        Return the indices for a subdomain in the grid.
I would rather leave it like this, since it's numpydoc standard to start the summary with an infinitive verb.

2025-01-17 13:31 UTC, jtodev commented on acoular/grids.py
> +        """Generate a unique digest for the grid."""
Unfortunately it leads to `IndentationError`s if a method is defined without a proper definition below. A docstring prevents the `IndentationError` in such cases. So I suggest we keep them with the underscore methods in the `Grid` class.

2025-01-17 14:04 UTC, jtodev commented on acoular/grids.py
> +    """
My mistake. I changed it.

2025-01-17 14:07 UTC, jtodev commented on acoular/grids.py
> +            Small tolerance value used for floating point comparisons when checking if a point
I guess it's supposed to mean `Tolerance used`. I changed it to that.

2025-01-17 14:09 UTC, jtodev commented on acoular/grids.py
> +        Tolerance allowed in the inside-triangle check. Default is `0`.
All right. I got it to work and also applied it in a couple of other places.

2025-01-20 08:35 UTC, adku1173 commented on acoular/grids.py
> +    p : ndarray of floats, shape `(N, K)`
NumPy ndarrays should be referenced with 
```
:class:`numpy.ndarray` to be referenced by inter-sphinx.

2025-01-20 08:39 UTC, adku1173 commented on acoular/grids.py
> +    ndarray of bool
Here, ndarray and bool should better be referenced:

```
:class:`numpy.ndarray` of :class:`bool`
```

2025-01-20 09:06 UTC, artpelling submitted a review, later dismissed

2025-01-20 09:06 UTC, artpelling commented on acoular/grids.py
> +    Provides a cartesian 3D grid for the beamforming results.
Then we need an infinite form here ;-)

2025-01-20 09:06 UTC, artpelling commented on acoular/grids.py
> +        Return the indices for a subdomain in the grid.
I agree. I wasn't aware of this standard.

2025-01-20 09:06 UTC, artpelling commented on acoular/grids.py
> +    Loads a 3D grid from an XML file.
also here. Please check again if we use infinite form everywhere :)

2025-01-20 13:48 UTC, adku1173 commented on acoular/grids.py
> +    #: The grid positions represented as a (3, :attr:`size`) array of floats. Invalid points, such
there is no functionality for invalid points. In addition, the current grid classes are not intended to be used as a microphone arrangement. Thus only `The grid positions represented as a (3, :attr:`size`) array of floats. (read-only)` makes sense

2025-01-20 13:48 UTC, adku1173 commented on acoular/grids.py
> +        """Generate a unique digest for the grid."""
I don't see any problem with having docstrings for private methods. If a private method becomes public, it already has a proper docstring. In this case, the getter needs to be overwritten by corresponding subclasses, and some documentation can benefit new developers. @artpelling adding `pass` should not change functionality.

2025-01-20 13:48 UTC, adku1173 commented on acoular/grids.py
> +        tuple of float
```suggestion
        tuple of floats
```

2025-01-20 15:09 UTC, jtodev commented on acoular/grids.py
> +        tuple of float
How about linking to the classes in all cases? So in this case ``` :class:`tuple` of :class:`float` ``` or maybe ``` :class:`tuple` of :class:`floats<float>` ```. What do you think?

2025-01-20 19:35 UTC, adku1173 commented on acoular/grids.py
> +        tuple of float
```
:class:`tuple` of :class:`floats<float>` 
```
looks good :)

2025-01-20 19:44 UTC, adku1173 commented on acoular/grids.py
> +    This class is used to import a 3D grid defined in an XML file. The grid's
There is one crucial thing missing here. As with all classes supporting file import, there is a way of specifying a custom grid as a NumPy array, similar to the classes `MicGeom` and `TimeSamples`. For these classes, the documentation should contain an example demonstrating that setting the `pos` attribute is possible.

2025-01-20 19:48 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = ac.grids.RectGrid3D()
All classes in acoular can be directly imported (see the init.py file, which is not empty). Thus, it is always enough to write

```suggestion
        >>> grid = ac.RectGrid3D()
```

2025-01-20 19:48 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = ac.grids.RectGrid3D()
```suggestion
        >>> grid = ac.RectGrid3D()
```

2025-01-20 19:51 UTC, adku1173 commented on acoular/grids.py
> +        >>> from acoular.grids import ImportGrid  # doctest: +SKIP
I prefer an example that writes a simple XML file (not with acoular since there is no `export_gpos` method) which is then loaded by the ImportGrid class. 

For consistency, I would prefer `import acoular as ac`

2025-01-20 19:53 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = RectGrid()
Why is no acoular import necessary here?

2025-01-20 19:56 UTC, adku1173 commented on acoular/grids.py
> +    #: Total length of the line in meters. Default is 1.0.
The values are not necessarily in meters. It depends on what the user defines as the unit of length.
```suggestion
    #: Total length of the line. Default is 1.0.
```

2025-01-20 19:58 UTC, adku1173 commented on acoular/grids.py
> +    #: invalid microphones. (read-only)
It's a source grid, not a microphone geometry (no invalid microphones).

2025-01-20 20:00 UTC, adku1173 commented on acoular/grids.py
> +    >>> grid = ac.grids.LineGrid()
```suggestion
    >>> grid = ac.LineGrid()
```

2025-01-20 20:01 UTC, adku1173 commented on acoular/grids.py
> +    >>> from acoular import grids
please use `import acoular as ac`

2025-01-20 20:35 UTC, adku1173 commented on acoular/grids.py
>      default_nearest = Bool(True, desc='return nearest grid point to center of none inside sector')
There is a typo, but even when fixing this, the sphinx docstring and trait description are unclear. `default_nearest` is an attribute, not a function. Thus, it can not return anything. Instead, it should mention its purpose and the method (`contains`) where the attribute becomes relevant. 

```suggestion
    default_nearest = Bool(True, desc='return nearest grid point to center if none inside sector')
```

2025-01-20 20:37 UTC, adku1173 commented on acoular/grids.py
> +    #: The minimum x position of the rectangle. Default is `-1.0`.
```suggestion
    #: The maximum x position of the rectangle. Default is `1.0`.
```

2025-01-20 20:38 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = ac.grids.RectGrid(increment=2)
```suggestion
        >>> grid = ac.RectGrid(increment=2)
```

2025-01-20 20:38 UTC, adku1173 commented on acoular/grids.py
> +        >>> sec = ac.grids.RectSector(x_min=0, y_min=0)
```suggestion
        >>> sec = ac.RectSector(x_min=0, y_min=0)
```

2025-01-20 20:39 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = ac.grids.RectGrid3D(increment=2)
```suggestion
        >>> grid = ac.RectGrid3D(increment=2)
```

2025-01-20 20:39 UTC, adku1173 commented on acoular/grids.py
> +        >>> sec = ac.grids.RectSector3D(x_min=0, y_min=0, z_min=0)
```suggestion
        >>> sec = ac.RectSector3D(x_min=0, y_min=0, z_min=0)
```

2025-01-20 20:40 UTC, adku1173 commented on acoular/grids.py
> +    This class inherits from :class:`SingleSector` and defines a circular sector, which can be used
```suggestion
    Defines a circular sector, which can be used
```

2025-01-20 20:41 UTC, adku1173 commented on acoular/grids.py
> +        >>> grid = ac.grids.RectGrid(increment=1)
```suggestion
        >>> grid = ac.RectGrid(increment=1)
```

2025-01-20 20:42 UTC, adku1173 commented on acoular/grids.py
> +        >>> sec = ac.grids.CircSector(x=1, y=1, r=0.5)
```suggestion
        >>> sec = ac.CircSector(x=1, y=1, r=0.5)
```

2025-01-20 20:56 UTC, adku1173 commented
@jtodev  It would be nice to include a reference to the sector integration example for the sector classes. This should be possible using the `:ref:` directive for the link `.. _sphx_glr_auto_examples_wind_tunnel_examples_example_sectors_and_integration.py:` pointing to the `acoular/docs/source/auto_examples/wind_tunnel_examples/example_sectors_and_integration.rst` example

2025-01-23 11:49 UTC, jtodev commented on acoular/grids.py
> +        >>> grid = RectGrid()
I don't know. `hatch run tests:doctest` works. But I will add `from acoular import RectGrid` out of rigorousness.

2025-01-23 11:57 UTC, jtodev commented on acoular/grids.py
> +        """Generate a unique digest for the grid."""
So I will just leave the docstrings there and make no further changes, right?

2025-01-23 12:01 UTC, jtodev commented on acoular/grids.py
> +    #: `True`. (optional)
Yes, I figured because of the default values. I removed it.

2025-02-18 11:56 UTC, adku1173 approved these changes

2025-02-18 19:36 UTC, adku1173 requested changes
@jtodev Unfortunately, the link to the sector integration example does not work as expected (-> it is not shown after building the docs).

2025-02-25 16:20 UTC, adku1173 approved these changes

2025-02-25 16:20 UTC, merged